;; Git
;;(require 'git-gutter-fringe)
(require 'git-gutter-fringe+)
;;(setq git-gutter-fr:side 'right-fringe)
;;(global-git-gutter-mode +1)
(global-git-gutter+-mode t)
;; (add-hook 'after-init-hook #'global-git-gutter-mode)
;; (setq git-gutter:window-width 2)
;; (setq git-gutter:unchanged-sign "  ")
;; (setq git-gutter:added-sign "++")
;; (setq git-gutter:deleted-sign "--")
;; (setq git-gutter:modified-sign "**")
;; (set-face-foreground 'git-gutter-fr:modified "yellow")
;; (set-face-foreground 'git-gutter-fr:added    "blue")
;; (set-face-foreground 'git-gutter-fr:deleted  "white")
;;(global-git-gutter-mode +1)
